### ISSUE TITLE
Doesn't work with latest version of chrome

### ISSUE THREAD

**Issue by petke** [jsakamoto/nupkg-selenium-webdriver-chromedriver#41]
The latest version of chrome (74.0.3729.108 (Official Build) (64-bit)), doesn't (seem to) work with the latest version of this nuget package (Selenium.WebDriver.ChromeDriver 73.0.3683.68).

Chrome has the annoying habit of updating version behind your back (and one cant revert back to old version as google doesn't provide downloads of old versions of chrome) .

 System.InvalidOperationException: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (....),platform=Windows NT 10.0.17134 x86_64) (SessionNotCreated)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
...

https://chromereleases.googleblog.com/2019/04/stable-channel-update-for-desktop_23.html

**Comment by GodStar88** [comment]
System.InvalidOperationException: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17763 x86_64) (SessionNotCreated)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)
   at Spotify.Classes.CWebbrowser.GoogleChrome(String username) in E:\Work\VC\Bot\09 - Other\other\Spotify\STREAM\soundcloud\soundcloud\Classes\CWebbrowser.cs:line 46
   at Spotify.Form1.PlaySong(Int32 number) in E:\Work\VC\Bot\09 - Other\other\Spotify\STREAM\soundcloud\soundcloud\Form1.cs:line 254

**Comment by jsakamoto** [comment]
In some reasons, I published the driver for v74 as a "pre-release" package.

If you are using Package Manager Console, please try do this:

![image](https://user-images.githubusercontent.com/95908/56702292-69ef7200-672d-11e9-8926-dae92da351dd.png)

or do this if you are using Package Manager GUI on Visual Studio:

![image](https://user-images.githubusercontent.com/95908/56702390-f1d57c00-672d-11e9-9881-d4a3faed56d4.png)

and, I also published latest official release v74 package just now.
You will find it on nuget.org after few minutes.

- https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/74.0.3729.6

**Comment by GodStar88** [comment]
thank you
