### ISSUE TITLE
Unable to call ChromeDriverService.CreateDefaultService(); in .NET Core

### ISSUE THREAD

**Issue by adrianwright109** [jsakamoto/nupkg-selenium-webdriver-chromedriver#42]
I have re-created a .NET Framework solution into a new .NET Core solution with 2 projects, a console app and class library.

I can use Visual Studio to successfully debug the .NET Framework solution but if I try to debug the .NET Core solution it fails to find `chromedriver.exe`

**Failing line:**
```
var driverService = ChromeDriverService.CreateDefaultService();
```

**Exception:**
```Exception type: OpenQA.Selenium.DriverServiceNotFoundException
Message       : The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.
Stacktrace:
   at OpenQA.Selenium.DriverService.FindDriverServiceExecutable(String executableName, Uri downloadUrl)
   at OpenQA.Selenium.Chrome.ChromeDriverService.CreateDefaultService()
   at WebDriverCommonLibraryCore.Browser..ctor()
        in C:\Users\Ady\GitHub\WebDriverCommonLibraryCore\WebDriverCommonLibraryCore\Browser.cs
        line 78
   at WebDriverCommonLibraryCore.Browser.get_Instance()
        in C:\Users\Ady\GitHub\WebDriverCommonLibraryCore\WebDriverCommonLibraryCore\Browser.cs
        line 108
   at BankCheckerCore.Program.Main(String[] args)
        in C:\Users\Ady\GitHub\BankCheckerCore\BankCheckerCore\Program.cs
        line 57
```

Project file Contents:

.NET Core Console App
**BankCheckerCore.csproj**
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <RootNamespace>BankCheckerCore</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;DEBUG;</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\WebDriverCommonLibraryCore\WebDriverCommonLibraryCore\WebDriverCommonLibraryCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="MerchantNameToExcelNameMappings.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

```

.NET Standard Class Library
**WebDriverCommonLibraryCore.csproj**
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE;_PUBLISH_CHROMEDRIVER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
    <PackageReference Include="Selenium.WebDriver" Version="3.141.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="74.0.3729.6" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.5.0" />
  </ItemGroup>

</Project>

```

The `chromedriver.exe` is in the .NET Core console app `.\bin\debug\netcoreapp2.2` folder as shown below:
![image](https://user-images.githubusercontent.com/47532258/56740812-8d381280-6769-11e9-910a-09dd47054973.png)

**Comment by adrianwright109** [comment]
This issue appears to be due to how .NET Core stores nuget packages.

For .NET Framework projects they would be stored in a `packages` folder for the project.  

For .NET Core they are now stored in a global place e.g. `C:\Users\{username}\.nuget\packages`

To fix it instead of using the default constructor to create the driver service
e.g.
```
var driverService = ChromeDriverService.CreateDefaultService();
```
I have used an alternative constructor which exists and takes in the `driverPath`
e.g.
```
var chromeDriverExePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
var driverService = ChromeDriverService.CreateDefaultService(chromeDriverExePath);
```
By doing this it now finds the `chromedriver.exe` in the `.\bin\debug\netcoreapp2.2` folder and I can once again debug the code.
