### ISSUE TITLE
Update to actual version ChromeDriver 93.0.4577.63

### ISSUE THREAD

**Issue by denhaandrei** [jsakamoto/nupkg-selenium-webdriver-chromedriver#84]
Hi, we got the following error: Your web driver may be out of date or unsupported. 
This happened between September 6, 2021, 12:19(works fine), and September 6, 2021, 19:05(stop working).
After analyzing the issue we take: The version ChromeDriver  91.0.4472.101 stopped support!!!

Update ChromeDriver to the 93.0.4577.15 version didn't help(return the same error). Because the actual package is 93.0.4577.63.
https://chromedriver.storage.googleapis.com/LATEST_RELEASE_93
**Please, can you update the ChromeDriver(93) to the 93.0.4577.63 packages**

```
Starting ChromeDriver  91.0.4472.101 (660fc11082ba57405eca2e8c49c3e1af756fbfae-refs/branch-heads/4577@{#203}) on port 16149
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Failed OpenChangePasswordPageTest [1 m 1 s]
Error Message:
Test method Tests.LoginTests.ChangePasswordPageTests.OpenChangePasswordPageTest threw exception: 
OpenQA.Selenium.WebDriverException: Your web driver may be out of date or unsupported. ---> OpenQA.Selenium.WebDriverException: Your web driver may be out of date or unsupported. ---> OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:16149/session timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out.

Stack Trace:
at System.Net.HttpWebRequest.GetResponse()
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
--- End of inner exception stack trace ---
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.<>c__DisplayClass7_0.<GetChromeDriver>b__0()
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.CreateDriver(Func`1 createFunction, Boolean retry)
--- End of inner exception stack trace ---
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.CreateDriver(Func`1 createFunction, Boolean retry)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.GetChromeDriver(TimeSpan commandTimeout, ChromeOptions chromeOptions, String size)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.GetBrowserWithDefaultConfiguration(BrowserType browser)
--- End of inner exception stack trace ---
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.GetBrowserWithDefaultConfiguration(BrowserType browser)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.GetDefaultBrowser()
at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumTest.GetBrowser()
at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumTest.<CreateNewTestObject>b__6_0()
at Magenic.Maqs.BaseSeleniumTest.SeleniumDriverManager.GetWebDriver()
at Magenic.Maqs.BaseSeleniumTest.SeleniumTestObject.get_WebDriver()
at Magenic.Maqs.BaseSeleniumTest.BaseSeleniumPageModel..ctor(SeleniumTestObject testObject)
at Models.WebPage.BasePageModel..ctor(SeleniumTestObject testObject) in ...\Models\BasePageModel.cs:line 23
at Models.LoginPageModel..ctor(SeleniumTestObject testObject) in ...\Models\WebPage\LoginPageModel.cs:line 23
at Tests.LoginTests.ChangePasswordPageTests.OpenChangePasswordPageTest() in ...\Tests\LoginTests\ChangePasswordPageTests.cs:line 27

Standard Output Messages:
The HTTP request to the remote WebDriver server for URL http://localhost:16149/session timed out after 60 seconds.
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.<>c__DisplayClass7_0.<GetChromeDriver>b__0()
at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.CreateDriver(Func`1 createFunction, Boolean retry)
The operation has timed out.
at System.Net.HttpWebRequest.GetResponse()
at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
```

**Comment by jsakamoto** [comment]
Oh, I'm sorry! 
I had missed the notification about released v.93.0.4577.63 even though I certainly received that notification e-mail.
Thank you for letting me know.

I rolled out the new Chrome driver package just now.

- https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/93.0.4577.6300

Please check it out.
Again, Thank you for your contribution!

**Comment by denhaandrei** [comment]
Thanks a lot for the quick update. Now I get the same error. Maybe the problem with some ChromeDriver 93.0.4577.63 updates because the latest version on the browser is  93.0.4577.82. I continue investigate this issue.

**Comment by denhaandrei** [comment]
Hi All, I found how to fix this issue. Use the following configuration with your ChromeDriver:

```
public class BaseTests : BaseSeleniumTest
{
        protected override IWebDriver GetBrowser()
        {
            var newOptions = WebDriverFactory.GetDefaultChromeOptions();
            newOptions.AddArgument("--no-sandbox");
            newOptions.AddArgument("--disable-gpu");

            return WebDriverFactory.GetChromeDriver(TimeSpan.FromSeconds(60), newOptions, "MAXIMIZE");
        }
...
```
